language: cpp

compiler:
  - gcc
#  - clang

before_install:
  - sudo pip install PyYAML
  - sudo pip install cpp-coveralls
  - git clone https://github.com/pfi/pficommon.git
  - pushd pficommon
  - ./waf configure
  - ./waf build
  - sudo ./waf install
  - popd
  - sudo ldconfig
  - wget http://google-styleguide.googlecode.com/svn/trunk/cpplint/cpplint.py
  - chmod +x cpplint.py
  - sudo mv cpplint.py /usr/local/bin

script:
  - ./waf configure --enable-gcov
  - ./waf build --checkall

after_success:
  - coveralls -b build -r . -E ".*_test.cpp" -E ".*/.unittest-gtest/.*" -E ".*pficommon/.*" -E".*/flip.hpp" -e test.cpp -x .cpp -x .hpp

branches:
  only:
    - master

notifications:
  email: false
