language: cpp

compiler:
  - gcc
#  - clang

before_install:
  - sudo pip install cpp-coveralls
  - wget http://sourceforge.net/projects/boost/files/boost/1.54.0/boost_1_54_0.tar.bz2
  - tar -jxf boost_1_54_0.tar.bz2
  - pushd boost_1_54_0
  - ./bootstrap.sh --help
  - sudo ./bootstrap.sh
  - sudo ./b2 install
  - popd

script:
  - ./waf configure --enable-gcov
  - ./waf build --checkall

after_success:
  - coveralls -E '.*_test.cpp'

branches:
  only:
    - master

notifications:
  email: false
