language: cpp

compiler:
  - gcc
#  - clang

before_install:
  - sudo pip install cpp-coveralls --use-mirrors
  - sudo apt-get install boost

script:
  - ./waf configure --enable-gcov
  - ./waf build --checkall

after_success:
  - coveralls --exclude lib --exclude tests

branches:
  only:
    - master

notifications:
  email: false
