def build(bld):
    bld.stlib(
        target='oxelon',
        source=[
            'bit_board.cpp',
            'bit_matrix.cpp',
            'position.cpp',
            ]
        )

    def make_test(target):
        bld.program(
            features='gtest',
            target=target,
            source=target + '.cpp',
            use='oxelon'
            )

    tests = [
        'bit_board_test',
        'bit_matrix_test',
        ]

    for t in tests:
        make_test(t)

